### ISSUE TITLE
Add /calendar link to the navigation bar

### ISSUE THREAD

**Issue by theawesomew** [coopsoc/website#30]
It seems fairly self-explanatory from the title. I'd like Jason or Sky to pick this one up!

**Comment by scorpiontornado** [comment]
@Sky828

**Comment by scorpiontornado** [comment]
Lmk if you need a hint with this one, but I think it'd be good if you could figure it out yourself

**Comment by premranjn** [comment]
Hey, Can I take part in it?

**Comment by premranjn** [comment]
I am a beginner in Open Source, What exactly adding calendar means here? I cant find any page related to calendar in here.....

**Comment by scorpiontornado** [comment]
Thanks for checking us out! I think I'll leave this issue to @Sky828 for now, but feel free to have a look around at the site.

If you're interested, we've set up a redirect from coopsoc.com.au/calendar to a custom ical link in cloudflare. All we need to do for this issue is add a hyperlink in the nav bar to take us to this url.

**Comment by theawesomew** [comment]
I'm going to steal this issue because we're being pressed on it.
